name: 'Compile native JS executables'

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

env:
  QJS_VERSION: "2021-03-27"

jobs:
  build-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        include:
          - { sys: mingw64, env: x86_64 }
          - { sys: mingw32, env: i686 }
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: msys2/setup-msys2@v2
        with:
          msystem: ${{matrix.sys}}
          install: >-
            wget
            unzip
            git
            mingw-w64-${{matrix.env}}-gcc
            mingw-w64-${{matrix.env}}-dlfcn
      - name: Change line Endings
        run: git config --global core.autocrlf input
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Cache Deno
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-deno-${{ hashFiles('**/*') }}
          restore-keys: ${{ runner.os }}-deno-
          path: |
            /home/runneradmin/.deno
            /home/runneradmin/.cache/deno/deps/https/deno.land
      - name: Setup deno
        run: |
          curl -fsSL https://deno.land/x/install/install.sh | sh
      - name: Cache QuickJS
        uses: actions/cache@v3
        id: cache-qjs-windows
        with:
          path: quickjs
          key: ${{ runner.os }}-${{ env.QJS_VERSION }}-${{ matrix.sys }}
      - name: Setup quickjs compiler
        if: steps.cache-qjs-windows.outputs.cache-hit != 'true'
        run: |
          wget https://github.com/mengmo/QuickJS-Windows-Build/releases/download/${{ env.QJS_VERSION }}/quickjs-${{ env.QJS_VERSION }}-win64-all.zip
          unzip quickjs-${{ env.QJS_VERSION }}-win64-all.zip -d quickjs

      - name: Build Deno and QuickJS release
        run: |
          /home/runneradmin/.deno/bin/deno task djs
          /home/runneradmin/.deno/bin/deno task qjs
          quickjs/bin/qjsc -e -o ./build/qjs65.c ./src/qjs.js
          gcc -v -D_GNU_SOURCE -Iquickjs/include/quickjs/ -o ./build/js65 ./build/qjs65.c -static -s -Lquickjs/lib/quickjs/ -lquickjs -lm -ldl -lpthread

      - name: Upload deno artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ runner.os }}-${{ matrix.env }}-deno
          path: |
            build/djs65*
      - name: Upload quickjs artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ runner.os }}-${{ matrix.env }}-quickjs
          path: |
            build/js65*

  build-other:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cache Deno
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-deno-${{ hashFiles('**/*') }}
          restore-keys: ${{ runner.os }}-deno-
          path: |
            /home/runner/.deno
            /home/runner/.cache/deno/deps/https/deno.land
      - name: Cache QuickJS
        uses: actions/cache@v3
        id: cache_qjs
        with:
          path: quickjs-${{ env.QJS_VERSION }}
          key: ${{ runner.os }}-${{ env.QJS_VERSION }}
      - name: Setup deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Setup quickjs compiler
        if: steps.cache_qjs.outputs.cache-hit != 'true'
        run: |
          wget https://bellard.org/quickjs/quickjs-${{ env.QJS_VERSION }}.tar.xz
          tar xf quickjs-${{ env.QJS_VERSION }}.tar.xz
          cd quickjs-${{ env.QJS_VERSION }}
          make -j4
      - name: Build Deno and QuickJS release
        run: |
          deno task djs
          deno task qjs
          quickjs-${{ env.QJS_VERSION }}/qjsc -o ./build/js65 ./src/qjs.js
      - name: Upload deno artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}-deno
          path: |
            build/djs65
      - name: Upload quickjs artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}-quickjs
          path: |
            build/js65
