name: 'Build and Test and deliver js65'

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  integration:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: ".bun-version"
      - name: Setup repo and install deps
        run: |
          bun install
      - name: Run Test Cases
        run: |
          bun test
      - name: Build Bun release
        run: |
          bun run exe
      - name: Build integration library
        run: |
          bun run lib
      - name: Build example integrations
        run: |
          dotnet build -c Release
      - name: Run example project
        run: |
          ./integrations/dotnet/example/bin/Release/net8.0/example
      - name: Pack nuget
        run: |
          dotnet pack -c Release --no-build --output build/

      - name: Upload bun artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-bun
          path: |
            build/js65*
      - name: Upload nuget artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-nuget
          path: |
            build/*.nupkg