name: 'Build and Test and deliver js65'

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  build-other:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: ".bun-version"
      - name: Setup repo and install deps
        run: |
          bun install
      - name: Run Test Cases
        run: |
          bun test
      - name: Build Bun release
        run: |
          bun run exe
      - name: Build CJS cli library
        run: |
          bun run lib
      - name: Upload bun artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}-bun
          path: |
            build/js65
