name: 'Link Checker: All English'

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

env:
  QJS_VERSION: "2021-03-27"

jobs:
  check-links:
    strategy:
      matrix:
        container: [dockcross/windows-static-x86, dockcross/windows-static-x64]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cache Deno
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-deno-${{ hashFiles('**/*') }}
          restore-keys: ${{ runner.os }}-deno-
          path: |
            /home/runner/.deno
            /home/runner/.cache/deno/deps/https/deno.land
      - name: Cache QuickJS
        uses: actions/cache@v3
        id: cache_qjs
        with:
          path: quickjs-$QJS_VERSION
          key: ${{ runner.os }}-${{ env.QJS_VERSION }}
      - name: Setup deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Setup quickjs compiler
        if: steps.cache_qjs.outputs.cache-hit != 'true'
        run: |
          wget https://bellard.org/quickjs/quickjs-$QJS_VERSION.tar.xz
          tar xf quickjs-$QJS_VERSION.tar.xz
          cd quickjs-$QJS_VERSION
          make -j4
      - name: Build Deno and QuickJS release
        run: |
          deno task djs
          deno task qjs
          quickjs-$QJS_VERSION/qjsc -e -o ./build/qjs65.c ./src/qjs.js
      - name: Cross Compile quickjs exe
        run: |
          docker run --rm ${{ matrix.container }} > ./dockcross
          chmod +x ./dockcross
          ./dockcross bash -c '$CC -I./quickjs-$QJS_VERSION/ -L./quickjs-$QJS_VERSION/ -D_GNU_SOURCE -o ./build/qjs65 ./build/qjs65.c -static -s -lquickjs -lm -ldl -lpthread'
