name: 'Link Checker: All English'

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  check-links:
    strategy:
      matrix:
        container: [dockcross/windows-static-x86, dockcross/windows-static-x64]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Setup quickjs compiler
        run: |
          wget https://bellard.org/quickjs/quickjs-2021-03-27.tar.xz
          tar xf quickjs-2021-03-27.tar.xz
          cd quickjs-2021-03-27
          make
      - name: Build Deno and QuickJS release
        run: |
          deno task djs
          deno task qjs
          qjsc -e -o ./build/qjs65.c ./src/qjs.js
      - name: Cross Compile quickjs exe
        uses: addnab/docker-run-action@v3
        with:
          image: ${{ matrix.container }}
          options: -v ${{ github.workspace }}:/work
          run: |
            $(CC) -I/work/quickjs-2021-03-27/ -L/work/quickjs-2021-03-27/ -D_GNU_SOURCE -o /work/build/qjs65 /work/build/qjs65.c -static -s -lquickjs -lm -ldl -lpthread
